<?php

/**
 * PHP array file.
 *
 * @author    Justin Tadlock <justintadlock@gmail.com>
 * @copyright Copyright (c) 2026, Justin Tadlock
 * @license   https://opensource.org/licenses/MIT MIT
 * @link      https://github.com/blush-dev/framework
 */

declare(strict_types=1);

namespace Blush\Support;

/**
 * A PHP file that returns an array, the format Blush uses for everything it
 * compiles ahead of time (config, container plans, extension discovery, and
 * so on). Reading one is a plain `include`, so opcache keeps it in shared
 * memory. Writes are atomic (temp file + rename), and the new file is
 * invalidated in opcache so the next read sees it.
 */
final readonly class PhpArrayFile
{
	public function __construct(public string $path)
	{}

	/**
	 * Whether the file exists.
	 */
	public function exists(): bool
	{
		return is_file($this->path);
	}

	/**
	 * Returns the file's array, or `null` when the file doesn't exist.
	 *
	 * @return ?array<array-key, mixed>
	 * @throws FilesystemException When the file doesn't return an array.
	 */
	public function read(): ?array
	{
		if (! $this->exists()) {
			return null;
		}

		$data = (static fn (string $path): mixed => include $path)($this->path);

		if (! is_array($data)) {
			throw new FilesystemException(sprintf(
				'Compiled file "%s" must return an array.',
				$this->path
			));
		}

		return $data;
	}

	/**
	 * Writes the array to the file, replacing it atomically.
	 *
	 * @param  array<array-key, mixed> $data
	 * @throws FilesystemException When the file can't be written.
	 */
	public function write(array $data): void
	{
		$contents = "<?php\n\n// Generated by Blush. Do not edit.\n\ndeclare(strict_types=1);\n\nreturn "
			. var_export($data, true)
			. ";\n";

		new Filesystem()->writeAtomic($this->path, $contents);

		if (function_exists('opcache_invalidate')) {
			opcache_invalidate($this->path, true);
		}
	}

	/**
	 * Deletes the file if it exists.
	 */
	public function delete(): void
	{
		if ($this->exists()) {
			unlink($this->path);
		}

		if (function_exists('opcache_invalidate')) {
			opcache_invalidate($this->path, true);
		}
	}
}
